common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *common
  database: erp_project_development

test:
  <<: *common
  database: erp_project_test

production:
  <<: *common
  database: erp_project_production