common: &common
  adapter: postgresql
  template: template0
  host: localhost

development:
  <<: *common
  database: erp_project_development

test:
  <<: *common
  database: erp_project_test

production:
  <<: *common
  database: erp_project_production